=== payu-org/payu/payu/telemetry/telemetry_config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "telemetry_url",
        "telemetry_token",
        "telemetry_service_name",
        "hostname"
    ],
    "additionalProperties": false,
    "properties": {
        "version": {
            "type": "string",
            "description": "The version of the telemetry configuration"
        },
        "telemetry_url": {
            "type": "string",
            "description": "The endpoint URL for the payu telemetry service"
        },
        "telemetry_proxy_url": {
            "type": "string",
            "description": "The proxy URL for the payu telemetry service"
        },
        "telemetry_token": {
            "type": "string",
            "description": "The authentication token for the payu telemetry service"
        },
        "telemetry_service_name": {
            "type": "string",
            "description": "The name of the service sending telemetry data"
        },
        "hostname": {
            "type": "string",
            "description": "The name of the HPC host where payu is running"
        }
    }
}

=== payu-org/payu/payu/telemetry/telemetry_config.json
{
    "version": "1.0",
    "telemetry_url": "{{ env['PAYU_TELEMETRY_URL'] }}",
    "telemetry_proxy_url": "{{ env['PAYU_TELEMETRY_PROXY_URL'] }}",
    "telemetry_token": "{{ env['PAYU_TELEMETRY_TOKEN'] }}",
    "telemetry_service_name": "{{ env['PAYU_TELEMETRY_SERVICE_NAME'] }}",
    "hostname": "{{ env['PAYU_TELEMETRY_HOSTNAME'] }}"
}
